---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hajimari-app
  namespace: flux-system
spec:
  path: ./kube/deploy/apps/hajimari/app
  dependsOn:
    - name: 1-core-ingress-nginx-app