apiVersion: v1
kind: Secret
metadata:
    name: biohazard-secrets-decrypt-sops-age
    namespace: flux-system
data:
    age.agekey: ENC[AES256_GCM,data:KZO64ZdjaIOfjZBPZMHHAJCuRI5WeQUoqy9/IsjQWeotD1/cXlBJnyrfAEEiQi3pHPRFxyc6ZA2j+HfROWSu7guCTud2uhlpfyk=,iv:2YkifdspMIcA/XdtLgOPfXfh5I0pTdnIc+etRs97ASU=,tag:fkmRxsRqmDWSUbMxRc8mPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZTMyNVpQdDVSZjlUNFhM
            dmJnZkROMkp0UmJlTHV5dUFJQ0Z0cVFjNEN3CkpOeWtkN253d3F6VXF2RDJEVDFD
            aHRldkxacVlCZUw4RmMvcjZGM2JTeWsKLS0tIHBIWmxjV0NzR2FWa2pMWFNabzJB
            aXQwUThFV0lQd2xZdk44YVhaNnhNS0kKZcBrSOxlM61d/BrZGNnMoxCu9Kxg6vpP
            pua71n+M5ZZdMmek3LeP3UMSi0QkmQbrhpExYUfMLPwASYbKXF50rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T07:14:42Z"
    mac: ENC[AES256_GCM,data:p8AJzfwX+3tqOoDwQbmBXalEybBO2Znr8g//fhVOChHDjeHqNmCETFZqNePhrWDLw0J8f+DUloGN00CQNKuzCex4TZ22+8HeUM5Lt3cCUGIfXR7Y749YAM6ri16Oon2rp+LefjeyRC3oNw9+ukKsS0BdkQsAPhUDdCxgDdd84oI=,iv:qNB7WhSTlddfOMpIvrpMWj4o6cgsWrKUbGdTBciOIjc=,tag:zrr6jcdYXXJiSaOwpI64+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
