keys:
  - &admin_bob age1yvl77vcj6cthafxqnjezrme4ntktjgd2j4xpgkcfutws83zrtdesk93cll
creation_rules:
  - path_regex: ((.local|pulumi|terraform)\/.*|(k8s|kube|kubernetes)\/.*tal.*)\.sops\.ya?ml
    input_type: yaml
    key_groups:
    - age:
      - *admin_bob
  - path_regex: (k8s|kube|kubernetes)\/.*\.sops\.ya?ml
    input_type: yaml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
    - age:
      - *admin_bob
  # - path_regex: (k8s|kube|kubernetes)/.*\.ya?ml
  #   input_type: yaml
  #   encrypted_regex: ^(data|stringData)$
  #   key_groups:
  #   - age:
  #     - *admin_bob
  - path_regex: (k8s|kube|kubernetes)/.*\.sops\.env
    input_type: env
    key_groups:
    - age:
      - *admin_bob