---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-file
  namespace: vault
spec:
  storageClassName: "block-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
