---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: longhorn-system
      interval: 5m
  values:
    annotations:
      vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    persistence:
      defaultClassReplicaCount: 1
      defaultFsType: ext4
    defaultSettings:
      defaultReplicaCount: 1
      defaultDataPath: /home/slim/storageb1
      defaultLonghornStaticStorageClass: block-storage
      backupTarget: s3://velero99@de/
      backupTargetCredentialSecret: minio-secret
      deletingConfirmationFlag: true
    longhornUI:
      replicas: 1
    pspEnable: false
    ingress:
      enabled: true
      ingressClassName: "nginx"
      tls: true
      host: "longhorn.${DNS_MAIN}"