apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_ENDPOINTS: "http://minio.storage.svc.cluster.local:9000"
  #AWS_CERT: your base64 encoded custom CA certificate goes here