---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-monitoring-deps
  namespace: flux-system
  labels:
    prune.flux.home.arpa/disabled: "true"
spec:
  path: ./kube/deploy/core/monitoring/_deps/app
  dependsOn:
    - name: 1-core-tls-cert-manager-crds