---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-app
  namespace: flux-system
spec:
  path: ./kube/deploy/apps/immich/app
  dependsOn:
    - name: 1-core-storage-longhorn-app