---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app redis
  namespace: redis
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
  values:
    global:
      fullnameOverride: *app
    # automountServiceAccountToken: false
    controller:
      type: deployment
      replicas: 1
    image:
      repository: public.ecr.aws/docker/library/redis
      tag: 7.0.11-bullseye
    command:
      - sh
    args:
      - -c
      - >-
        redis-server --requirepass $REDIS_PASSWORD
    # podAnnotations:
      # vault.security.banzaicloud.io/vault-addr: "http://vault.vault.svc.cluster.local:8200"
    env:
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "vault:secret/data/redis#PASSWORD"
    service:
      main:
        ports:
          http:
            port: 6379
    resources:
      requests:
        cpu: 10m
        memory: 204Mi
      limits:
        memory: 512Mi
