---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app hajimari
  namespace: *app
spec:
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        name: hajimari
        kind: HelmRepository
        namespace: hajimari
  values:
    env:
      TZ: America/New_York
    hajimari:
      title: Apps
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: false
      showAppStatus: false
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "home.${DNS_MAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M