---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  loadBalancerIPs: true
  interfaces:
    - ^enp.*
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  cidrs:
    - cidr: "${IP_LB_CIDR}"
# ---
# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumLoadBalancerIPPool
# metadata:
#   name: dns
# spec:
#   cidrs:
#     - cidr: "${IP_LB_DNS_CIDR}"
#   serviceSelector:
#     matchLabels:
#       exposeSvc: dns