apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault
spec:
  chart:
    spec:
      chart: vault-operator
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
  interval: 5m
  install:
    remediation:
      retries: 100
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-webhook
  namespace: vault
spec:
  chart:
    spec:
      chart: vault-secrets-webhook
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
  interval: 5m
  install:
    remediation:
      retries: 100
