---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-storage-longhorn-app
  namespace: flux-system
spec:
  path: ./kube/deploy/core/storage/longhorn/app
  dependsOn: 
    - name: 1-core-kyverno-app
